# 代码生成
gen: 
  # 作者
  author: kunyuesoft
  # 默认生成包路径 system 需改成自己的模块名称 如 system monitor tool
  packageName: com.kunyuesoft
  # 自动去除表前缀，默认是true
  autoRemovePre: false
  # 表前缀（生成类名不会包含表前缀，多个用逗号分隔）
  tablePrefix: sys_

# MyBatis配置
mybatis:
  # 搜索指定包别名
  typeAliasesPackage: com.kunyuesoft.gen.**.domain
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath:mapper/*Mapper.xml
  # 加载全局的配置文件
  configLocation: classpath:mybatis-config.xml



# 数据源配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/kunyuesoft?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=convertToNull&useSSL=true&rewriteBatchedStatements=true
    username: root
    password: qpy1995
    driver-class-name: com.mysql.jdbc.Driver